Vagrant.configure("2") do |config|

  config.vm.box = "scotch/box"
  config.vm.hostname = "env-lamp"

  # Configurate the virtual machine to use 2GB of RAM
  config.vm.provider :virtualbox do |v|
    v.memory = 4096
    v.cpus = 2
  end

  # Forward the Rails server default port to the host
  config.vm.network "private_network", ip: "192.168.33.10"

  # Add directory sync
  config.vm.synced_folder ".", "/var/www/public", mount_options: ["dmode=777", "fmode=777"], fsnotify: true

  # Add custom actions
  config.vm.provision :shell, path: 'bootstrap.sh', keep_color: true

end
